#!/usr/bin/env bash
sudo apt-get install -y vim screen
mkdir ~/binaries
cd ~/binaries
wget https://github.com/prometheus/prometheus/releases/download/v1.0.2/prometheus-1.0.2.linux-amd64.tar.gz > /dev/null
wget https://github.com/prometheus/alertmanager/releases/download/v0.4.1/alertmanager-0.4.1.linux-amd64.tar.gz > /dev/null
wget https://github.com/prometheus/node_exporter/releases/download/0.12.0/node_exporter-0.12.0.linux-amd64.tar.gz > /dev/null
wget https://storage.googleapis.com/golang/go1.7.linux-amd64.tar.gz > /dev/null
tar xvfz go1.7.linux-amd64.tar.gz > /dev/null
mkdir ~/go
sudo mv go /usr/local
export GOPATH=~/go
export PATH=$PATH:/usr/local/go/bin
echo 'export GOPATH=~/go' >> ~/.profile
echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.profile
go get github.com/mesosphere/mesos-exporter
tar xvfz prometheus-1.0.2.linux-amd64.tar.gz > /dev/null
tar xvfz alertmanager-0.4.1.linux-amd64.tar.gz > /dev/null
tar xvfz node_exporter-0.12.0.linux-amd64.tar.gz > /dev/null
cp /vagrant/commands/setup/prometheus.yml ~/binaries/prometheus-1.0.2.linux-amd64/
cp /vagrant/commands/setup/alertmanager.yml ~/binaries/alertmanager-0.4.1.linux-amd64/
cd /vagrant/commands/
./prometheus
./containers-metrics 
./dockers            
./grafana            
./mesos-exporters    
cd dashboards
./build.sh
