#!/usr/bin/env bash
screen -S mesos-exporter-master -dm ~/go/bin/mesos-exporter -master http://`ip addr show eth1 | grep inet\  | awk '{print $2}' | cut -d/ -f1`:5050
screen -S mesos-exporter-slave -dm ~/go/bin/mesos-exporter -addr=":9111" -slave http://`ip addr show eth1 | grep inet\  | awk '{print $2}' | cut -d/ -f1`:5051
